# ClearBounce Status Page Configuration
owner: tlgcklr
repo: clearbounce-status-

# Monitored sites
sites:
  - name: Website
    url: https://www.clearbounce.net
    icon: https://www.clearbounce.net/favicon.ico

  - name: Dashboard
    url: https://www.clearbounce.net/dashboard/
    expectedStatusCodes:
      - 200
      - 403

  - name: API
    url: https://www.clearbounce.net/api/v1/health
    expectedStatusCodes:
      - 200
      - 404

  - name: Shield Widget
    url: https://www.clearbounce.net/shield/widget.js
    expectedStatusCodes:
      - 200

# Status page settings
status-website:
  cname: status.clearbounce.net
  logoUrl: https://www.clearbounce.net/logo.png
  favicon: https://www.clearbounce.net/favicon.ico
  name: ClearBounce Status
  theme: dark
  introTitle: "**ClearBounce** Sistem Durumu"
  introMessage: Tüm servislerimizin gerçek zamanlı durumunu buradan takip edebilirsiniz. Herhangi bir sorun olduğunda bu sayfa otomatik olarak güncellenir.
  navbar:
    - title: Ana Sayfa
      href: https://www.clearbounce.net
    - title: Dashboard
      href: https://www.clearbounce.net/dashboard
    - title: API Docs
      href: https://www.clearbounce.net/docs

# Turkish translations
i18n:
  activeIncidents: Aktif Sorunlar
  pastIncidents: Geçmiş Sorunlar
  pastIncidentsResolved: Çözülen Sorunlar
  allSystemsOperational: Tüm sistemler çalışıyor
  incidentReport: Olay raporu →
  incidentFixed: Düzeltildi
  incidentOngoing: Devam ediyor
  incidentScheduled: Planlı bakım
  incidentDetails: Detaylar
  uptimeHistory: Çalışma süresi geçmişi
  responseTimeHistory: Yanıt süresi geçmişi
  up: Çalışıyor
  down: Çalışmıyor
  degraded: Yavaş
  ms: ms
  loading: Yükleniyor
  liveStatus: Canlı durum
  overallUptime: Genel çalışma süresi
  responseTime: Yanıt süresi
  averageResponseTime: Ortalama yanıt süresi
  day: Gün
  days: Gün
  hour: Saat
  hours: Saat
  minute: Dakika
  minutes: Dakika
  second: Saniye
  seconds: Saniye
  navHome: Ana Sayfa
  navGitHub: GitHub
  navStatus: Durum
  footer: "Bu sayfa [Upptime](https://upptime.js.org) ile oluşturulmuştur."

# Check frequency
workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 1 * *"
  uptime: "*/5 * * * *"
